print("Operatory w pythonie: \n")
print("< - mniejsze od")
print("> - wieksze od")
print("!= - rozne")
print("== - rowne")
print("<= - mniejsze badz rowne")
print(">= - wieksze badz rowne")
print("and – obydwa warunki muszą być prawdziwe")
print("or – jeden z warunkow musi być prawdziwy")